# Configuration
config:
  # MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
      - table
      - tr
      - td
      - th
      - tbody
      - thead
      - tfoot
      - colgroup

# Globs
globs:
  - "**/*.md"
  - "*.md"

# Fix any fixable errors
fix: true