# Configuration

config:
  # MD013 - line-length
  line_length:
    line_length: 140
    code_blocks: false
    tables: false
  no-inline-html: false

# Globs

globs:
  - "dotclaude/agents/**/*.md"
  - "dotclaude/agents/*.md"
  - "dotclaude/commands/**/*.md"
  - "dotclaude/commands/*.md"
  - "dotclaude/output-styles/**/*.md"
  - "dotclaude/output-styles/*.md"
  - ".claude/agents/**/*.md"
  - ".claude/agents/*.md"
  - ".claude/commands/**/*.md"
  - ".claude/commands/*.md"
  - ".claude/output-styles/**/*.md"
  - ".claude/output-styles/*.md"

# Fix any fixable errors

fix: true

# Define a custom front matter pattern

frontMatter: ^(---\n[^]*?^---)(\n|$)

# Ignore files referenced by .gitignore (only valid at root)

gitignore: true

# Show found files on stdout (only valid at root)
showFound: true
