# Configuration

config:
  # MD013 - line-length
  line_length:
    line_length: 140
    code_blocks: false
    tables: false
    headings: false
  no-inline-html: false
  heading-style:
    style: atx
  first-line-h1: false

# Globs

globs:
  - "README.md"

# Fix any fixable errors

fix: true

# Define a custom front matter pattern

frontMatter: ^(\[!\[[-\w\. ]+\]\([^\)]+\)\]\([^\)]+\)\n)*

# Ignore files referenced by .gitignore (only valid at root)

gitignore: true

# Show found files on stdout (only valid at root)
showFound: true
